### ISSUE TITLE
Implement arkworks <-> zexe circuit serialization to initialize phase 2

### ISSUE THREAD

**Issue by kobigurk** [celo-org/snark-setup-operator#56]

**Comment by mrsmkl** [comment]
I did some work on serializing the circuit, seems quite straightforward
the changes are in these branches:
* https://github.com/celo-org/snark-setup/compare/straka/phase2_integration...mrsmkl:mrsmkl/load-circuit?expand=1
* https://github.com/celo-org/celo-bls-snark-rs/compare/kobigurk/arkworks...mrsmkl/serialize-circuit
I only tested that the phase2 setup can deserialize the circuit, I don't know how to do e2e test for phase2 yet

**Comment by kobigurk** [comment]
@mstraka100 can we close this?
