### ISSUE TITLE
Improve handling of uploads in unreliable/slower connections

### ISSUE THREAD

**Issue by kobigurk** [celo-org/snark-setup-operator#57]
It seems that our handling of uploads in unreliable/slower connections can be improved.

We see the following issues:
* On a slower connection, a participant timed out. Enlarging the timeout (https://github.com/celo-org/snark-setup-operator/blob/60c947a2c855f153422be83a30e9b62ac6e5016e/src/utils.rs#L8) improved the situation significantly and the participant was able to make great progress. We tried to saturate the upload link (https://github.com/celo-org/snark-setup-operator/blob/60c947a2c855f153422be83a30e9b62ac6e5016e/src/blobstore.rs#L95), but we may have been over-zealous - we divide the files (the largest of which are around 700mb) into 1mb chunks and create async futures for all the 700 chunks. Perhaps what happens is that all of these happen concurrently, as each of the futures yield to I/O and so they don't wait for the others to complete. Let's assume that we can tolerate contributions of up to 36 hours, which means 0.5 megabytes per second. If we have 700 chunks of 1 megabytes running concurrently, then they might finish after 1400 seconds, and so a timeout of 300 seconds is not enough. Off the top of my head, I think the best way to handle it is to limit concurrency better (e.g. have 50 futures at a time rather than 700, wait for them, and only then continue to process the rest). Another way could be to enlarge the timeout, but it feels more brittle.

* Sometimes participants get status 400 instead of 201 (= Created). I think this happens when a chunk is retried. That might mean that our retry mechanism for uploads doesn't work in some or all cases. We should find a way to simulate a bad connection and see whether we need to perform some cleanup before retrying.

**Comment by mrsmkl** [comment]
I think @kobigurk already implemented this in https://github.com/celo-org/snark-setup-operator/pull/58

**Comment by kobigurk** [comment]
> I think @kobigurk already implemented this in #58

Yep!
