### ISSUE TITLE
Test phase2 integration end to end

### ISSUE THREAD

**Issue by mstraka100** [celo-org/snark-setup-operator#60]
After phase2 has been integrated into snark-setup-operator and snark-setup-coordinator, end-to-end testing should be done using both the snark-setup-coordinator and snark-setup-operator repos to ensure both work together properly

**Comment by mstraka100** [comment]
Steps to take in testing:

-Create an end-to-end script to test phase 1, prepare phase 2, and phase 2 running sequentially
-Run the above script locally and on Azure
-Run the above script with both the zexe Plumo circuit and the arkworks Plumo circuit
-Take the output of the end-to-end script and ensure the output parameters work with the snark-setup prover

**Comment by kobigurk** [comment]
@mstraka100 can we close this?
